### PR TITLE
Resolve #105 (sharing library browser) and change share UI

### LINKED ISSUE #105: cloo.gl integration in /src
This should be similar to `cloo.gl` integration on the frontpage.

### PR DESCRIPTION
**Pull request by camilstaps**
- On the main page, let an input field appear with the shortened URL
- On the main page, remove text-decoration and pointer cursor when the URL is being shortened
- Adds a share button to the library browser that turns into a text input field with the shortened URL

### CODE REVIEW

**Comment by dopefishh** [comment]
I'm not fond of the button on the source page. Moreover the text shown when making a shortlink on the frontpage is also a bit strange. Do we even need to change the text? Maybe we can let it be `Share`

**Comment by camilstaps** [comment]
> I'm not fond of the button on the source page.

What do you suggest?

> Moreover the text shown when making a shortlink on the frontpage is also a bit strange.

Would removing "Done, ", i.e. just "See URL below" help? If not: what exactly do you find strange about it?

> Do we even need to change the text? Maybe we can let it be `Share`

I don't think this is a good idea, then it is not clear for the user that something is happening. Also, on slow internet, you will see a text between sending the request and receiving the response; "Contacting cloo.gl server". This text should remain there, because otherwise on slow connections you will not see anything happening until the response is received. If the text then changes back to "Share" that would be unlogical.

**Comment by dopefishh** [comment]
Just leave the text as `Share`. Something like this: https://cloo.gl/MTEz

**Comment by dopefishh** [comment]
On `src` it might be better to not remove the button and just make the text `Share`

**Pull request merged**
