### PR TITLE
Auto clear form on submit

### PR DESCRIPTION
**Pull request by KDercksen**

### CODE REVIEW

**Comment by camilstaps** [comment]
Why?

**Comment by camilstaps** [comment]
E.g. when searching for a type, if you _just_ got the type wrong you want to edit it.

If we're going to clear the input, then we should at least show it somewhere.

**Comment by KDercksen** [comment]
This was behaviour mentioned by one of the students today as being not intuitive. I personally don't mind but thought you were referring to this when we left this afternoon. Feel free to close if not clearing is actually intended behaviour. :smile:

**Comment by camilstaps** [comment]
It works the same as in DuckDuckGo (and Google), I personally don't see how it is counter-intuitive. That student may be interested in following the instructions in the readme for setting up their own Cloogle server.

**Pull request closed without merging**
