### PR TITLE
Library browser

### PR DESCRIPTION
**Pull request by camilstaps**
This implements #90.

### CODE REVIEW

**Comment by dopefishh** [comment]
Mersennetwister still broken

**Comment by dopefishh** [comment]
http://localhost/src/view.php?lib=SoccerFun/Game#FootballerFunctions;line=13
is also broken, not sure why yet.

**Comment by dopefishh** [comment]
This is working now, however, one might not agree with the hack I had to apply to fix SoccerFun...

**Comment by camilstaps** [comment]
That's a problem with SoccerFun; it uses an ancient structure which I don't think we need to support. I made some minor changes to remove build warnings, improve some styling in the library browser and put back MersenneTwister, which is still in the Clean 2.4 distribution and used in gast.

**Comment by dopefishh** [comment]
There should be a Deprecated MersenneTwister interface that you can import if you want to support archaic interfaces.

Anyway, this looks good, if these are no more things te fix let's merge.

**Comment by camilstaps** [comment]
I agree, it should be done similarly to StdLib.

**Pull request merged**
