### PR TITLE
New logo and layout changes

### PR DESCRIPTION
**Pull request by ErinvanderVeen**
- SVG over JPG for better scaling while preserving small size
- Inspired by Clean logo
- CC-BY license for compatibility with the MIT license

### CODE REVIEW

**Comment by dopefishh** [comment]
If we change the logo we will never be reminded of the fact that the first version was just a big grep in the source tree...
If @camilstaps approves we can merge.

**Comment by camilstaps** [comment]
I think this looks great, but we need some UI redesign to make it fit. I changed the header in the [new-header branch](https://github.com/clean-cloogle/cloogle/tree/new-header); it now gives more space to the search results (see #88).

Unless somebody has problems with this new layout, I suggest we merge it together.

I tried to add a "With eternal thanks to PCRE" and a link to one of the earliest commits in the footer, but getting the alignment right would cost a lot of CSS and I am already unhappy about the size of frontend.css.

There is one minor issue with the logo; the `e` seems to be cut off. This is probably a browser issue, so converting to PNG in update.sh or so should fix that.

Screenshots of the new header:

2017-03-21-223640_644x324
2017-03-21-223648_714x627

**Comment by camilstaps** [comment]
Actually converting to PNG first (a3d1654) already helped, but now it is fixed completely; thanks.

**Comment by camilstaps** [comment]
Just realised that this almost certainly breaks on mobile. Should be fixed before merging.

**Comment by ErinvanderVeen** [comment]
Should no longer break on mobile.

**Comment by camilstaps** [comment]
I think this looks nice, with some minor remarks:

On the initial page, I'd like to center the three links under the search bar by setting the `padding` of the `ul` to 0. It seems more uniform that way. The background colour for the tooltips is very subtle, and on Radboud university screen quality is sometimes ... doubtful, so perhaps a stronger background colour like `#f8f8f8` would be better. For the advanced search options, some top/bottom padding is missing (because it does not use `<p>`).

2017-03-22-185948_368x249

On the search view, aligning the search bar to the baseline of the Cloogle logo looks nicer to me (which is of course entirely subjective). Here, I would remove some space between the search bar and the links. The content of the tooltips could be moved to directly under the search form, so that all search options are visible at a single glance. Some bottom margin for the tooltip can be added to put white space before the search results.

2017-03-22-190819_576x541

I'm also willing to make these changes myself of course :)

**Comment by ErinvanderVeen** [comment]
@camilstaps I considered a stronger background, like fafafa, but the problem was that such colors would interfere with the code in the "How to use" section.

**Comment by camilstaps** [comment]
Yeah, we can always change those colours (nobody uses that section anyway). `#eeeeee` looks fine to me. And a `border-radius: 2px` could be added to those code spans as well, not sure why that hasn't been done yet.

2017-03-22-191850_456x173

**Pull request merged**
